package net.corda.v5.application.uniqueness.model

import net.corda.v5.application.crypto.DigitalSignatureAndMetadata

/**
 * This data class is a wrapper for the result that was generated by the uniqueness
 * checker and a potential signature if the result was successful. This type is
 * returned by the uniqueness client service.
 *
 * @param result This is the actual result returned by the uniqueness checker
 * @param signatureAndMetadata The signature returned by the uniqueness checker,
 * might be `null` if the [result] is [UniquenessCheckResult.Failure].
 */
data class UniquenessCheckResponse(
    val result: UniquenessCheckResult,
    val signatureAndMetadata: DigitalSignatureAndMetadata?
)