pipeline {
    agent {
        docker {
            // Our custom docker image
            image 'build-zulu-openjdk:11'
            label 'docker'
            registryUrl 'https://engineering-docker.software.r3.com/'
            registryCredentialsId 'artifactory-credentials'
            // Used to mount storage from the host as a volume to persist the cache between builds
            alwaysPull true
        }
    }

    triggers {
        cron(env.BRANCH_NAME =~ /^release\/.*$/ ? '''\
            TZ=Europe/London
            30 06 * * *
        '''.stripIndent() : '')
    }

    environment {
        ARTIFACTORY_CREDENTIALS = credentials('artifactory-credentials')
        CORDA_ARTIFACTORY_USERNAME = "${env.ARTIFACTORY_CREDENTIALS_USR}"
        CORDA_ARTIFACTORY_PASSWORD = "${env.ARTIFACTORY_CREDENTIALS_PSW}"
        CORDA_USE_CACHE = "corda-remotes"
    }

    options {
        buildDiscarder(logRotator(daysToKeepStr: '14', artifactDaysToKeepStr: '14'))
        timeout(time: 120, unit: 'MINUTES')
        timestamps()
    }

    stages {
        stage('Adopt Open JDK') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    build job: "Corda5/corda5-compatibility-tests-jobs/corda5-compatibility-tests-adopt/${env.BRANCH_NAME.replace("/","%2F")}"
                }
            }
        }
        stage('Adopt Open J9 JDK') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    build job: "Corda5/corda5-compatibility-tests-jobs/corda5-compatibility-tests-openj9/${env.BRANCH_NAME.replace("/","%2F")}"
                }
            }
        }
        stage('Corretto') {
            steps {
                // Stop Error in Corretto from bubbling up until CORE-1200 is resolved
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    build job: "Corda5/corda5-compatibility-tests-jobs/corda5-compatibility-tests-corretto/${env.BRANCH_NAME.replace("/","%2F")}"
                }
            }
        }
        stage('Linux One') {
            steps {
                // We expect Linux One to fail
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    build job: "Corda5/corda5-compatibility-tests-jobs/corda5-compatibility-tests-linuxone/${env.BRANCH_NAME.replace("/","%2F")}"
                }
            }
        }
        stage('Windows') {
            steps {
                // We expect Windows to fail
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    build job: "Corda5/corda5-compatibility-tests-jobs/corda5-compatibility-tests-windows/${env.BRANCH_NAME.replace("/","%2F")}"
                }
            }
        }
    }
}
