name: Sync assigned jira issues

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  sync_assigned:
    runs-on: ubuntu-latest
    steps:
      - name: Assign
        uses: corda/jira-sync-assigned-action@master
        with:
          jiraBaseUrl: ${{ secrets.JIRA_BASE_URL }}
          jiraEmail: ${{ secrets.JIRA_USER_EMAIL }}
          jiraToken: ${{ secrets.JIRA_API_TOKEN }}
          token: ${{ secrets.GH_TOKEN }}
          owner: corda
          repository: corda
